### ISSUE TITLE
Feature Request: CRTK-ROS bridge required interfaces

### ISSUE THREAD

**Issue by htp2** [jhu-cisst/cisst-ros#15] opened 2021-10-28 15:22 UTC
It would be useful to extend the crtk_cisst_ros_bridge to also allow for easy bridging of required interfaces, similar to the current one-liners for provided interfaces we have currently: (bridge_interface_provided and bridge_all_interface_provided)

I would be able to use this immediately in my work (though I can work without it just fine for now), and would be willing to help with testing and development to the extent that I would be useful. I think it would greatly increase the usability of the cisst-ros bridge for a lot of users and encourage the use of CRTK conventions, both of which are really good things from my perspective.

I understand there would be some challenges regarding handling 'optional' items in cisst required interfaces (i.e. do you try to connect to a ROS topic if optional?, Do you check to see if it exists first?, Do you need a configuration file for the user to tell you what optional ones should be included?, etc.). I'm happy to participate in any brainstorming regarding how to handle these issues.

I spoke with @adeguet1 regarding this, tagging you here for your visibility.

Thanks!

**Comment by adeguet1** [comment] 2021-11-12 15:45
I pushed a bare bone version of the code to support this feature.  It is not documented nor extensively tested.  It also misses code to parse a JSON file to configure the bridge (will be required for dynamic creation).  To be consistent, I renamed `mts_ros_crtk_bridge` to `mts_ros_crtk_bridge_provided` which is used to bridge to a provided interface.  The new class is called `mts_ros_crtk_bridge_required` which is used to bridge to a required interface. 

To populate the bridge, I can think of 3 scenarios:
* Look at a required interface and assume everything will come from ROS.  Not great for MTS_OPTIONAL features but might work for some users.  This code is written but not tested yet.
* Explicitly list the commands we want to provide.  The code is written and somewhat tested using a C++ method.  See https://github.com/jhu-dvrk/dvrk-ros/blob/8578cbd716d014d236370b3e01c68a09efaf2e97/dvrk_arms_from_ros/components/src/dvrk_arm_from_ros.cpp#L47.  I still have to add code to populate from a configuration file.  
* Populate from ROS topics in a namespace.  I'm not sure how convenient that is.  It would also be dependent of the order nodes are started: if the cisst application is started too early the topics might not exist.  I don't plan to implement this.

Use:
* https://github.com/jhu-dvrk/dvrk-ros/commit/8578cbd716d014d236370b3e01c68a09efaf2e97
* https://github.com/jhu-saw/sawNDITracker/commit/4cdae5c39927e8c9904442e45674366ce4eff03d

Todo:
* Documentation
* Maybe some missing CRTK commands
* Add configuration file parsing
* Port same behavior to ROS 2 CRTK bridge

@htp2, thoughts?  Usable as is?

**Comment by htp2** [comment] 2021-11-14 19:10
@adeguet1 Just wanted to let you know I've seen this - thanks for adding this! I will test it as soon as I can (hopefully Mon or Tue).

**Comment by htp2** [comment] 2021-11-16 14:18
Hi Anton,

I am having some trouble getting this built on my machine. I also am using sawNDITracker. I updated to the most recent devel branch there but get this error on ```catkin build```

```
/home/henry/bigss/catkin_ws/src/cisst-saw/sawNDITracker/ros/mts_ros_crtk_ndi_bridge.cpp: In member function ‘void mts_ros_crtk_ndi_bridge::bridge(const string&, const string&, double, double)’:
/home/henry/bigss/catkin_ws/src/cisst-saw/sawNDITracker/ros/mts_ros_crtk_ndi_bridge.cpp:36:5: error: ‘mts_ros_crtk’ has not been declared
     mts_ros_crtk::clean_namespace(_clean_namespace);
```

I thought that maybe it should be ```mts_ros_crtk_bridge```, but I get the same error. Am I missing something?

**Comment by adeguet1** [comment] 2021-11-16 15:18
I likely forgot to commit and/or push my sawNDITracker changes.  I think all you need is to `#include` the `mts_ros_crtk_bridge.h` file.  I don't have access to the computer I used for this work but I should be able to push the changes tomorrow morning.

**Comment by adeguet1** [comment] 2021-11-16 15:25
That's odd.  I don't have access to the computer I used for this code so I can't test until tomorrow.  Can you add  `#include <cisst_ros_crtk/mts_ros_crtk_bridge_provided.h>` in: https://github.com/jhu-saw/sawNDITracker/blob/4cdae5c39927e8c9904442e45674366ce4eff03d/ros/mts_ros_crtk_ndi_bridge.h#L22 and see if that helps.

**Comment by adeguet1** [comment] 2021-11-18 19:22
I think the issue is now fixed.  You will need to pull the latest devel branch for cisst-ros and sawNDITracker.  Can you give it a try when you have some spare time?

**Comment by htp2** [comment] 2021-11-18 23:51
This did fix the issue - compiled without any problem! I'll keep you updated as I try to integrate this feature into our codebase

**Comment by htp2** [comment] 2022-08-09 17:54
Hi Anton, I know it's been a while since you worked on this or we talked about it. I had an application to test it with recently and it worked quite well. I had to make one small addition for the bridge_required to connect appropriately. Additionally, for my application, I wanted to be able to bridge servo_jv so I added that functionality in as well. Both are in a pull request #17

**Closed** 2022-08-10 15:18 UTC
